{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "g4uFXkypcnNh"
      },
      "outputs": [],
      "source": [
        "###############################################################\n",
        "# Time Series Analysis: Acme United Corporation Stock (ACU)\n",
        "# Author: MITESH KUMAR (M23MAC004)\n",
        "# Date: March 2025\n",
        "# Description: Analysis and forecasting of ACU stock prices\n",
        "###############################################################\n",
        "\n",
        "# Load required libraries\n",
        "library(quantmod)\n",
        "library(forecast)\n",
        "library(ggplot2)\n",
        "library(tseries)\n",
        "\n",
        "# Create plots directory if it doesn't exist\n",
        "if (!dir.exists(\"plots\")) {\n",
        "  dir.create(\"plots\")\n",
        "}\n",
        "\n",
        "# Source helper functions\n",
        "source(\"analysis_functions.R\")\n",
        "\n",
        "# Part 1: Data Acquisition and Preparation\n",
        "# ----------------------------------------\n",
        "\n",
        "# Fetch ACU data from Yahoo Finance (from 2020-10-21 to 2024-10-20)\n",
        "message(\"Fetching ACU stock data from Yahoo Finance...\")\n",
        "y <- getSymbols(\"ACU\", src = \"yahoo\", from = as.Date(\"2020-10-21\"), to = as.Date(\"2024-10-20\"), auto.assign = FALSE)\n",
        "\n",
        "# Convert to time series object using the closing price\n",
        "y_ts <- ts(y[, \"ACU.Close\"], start = c(2020, 10), frequency = 365)\n",
        "\n",
        "# Save raw data\n",
        "saveRDS(y_ts, file = \"data/acu_ts_data.rds\")\n",
        "\n",
        "# Basic statistics\n",
        "summary_stats <- data.frame(\n",
        "  Min = min(y_ts, na.rm = TRUE),\n",
        "  Max = max(y_ts, na.rm = TRUE),\n",
        "  Mean = mean(y_ts, na.rm = TRUE),\n",
        "  Median = median(y_ts, na.rm = TRUE),\n",
        "  SD = sd(y_ts, na.rm = TRUE)\n",
        ")\n",
        "write.csv(summary_stats, \"data/summary_statistics.csv\", row.names = FALSE)\n",
        "\n",
        "# Part 2: Data Visualization\n",
        "# --------------------------\n",
        "\n",
        "# 1. Plot time series data\n",
        "plot_ts <- autoplot(y_ts) +\n",
        "  ggtitle(\"Time Series Plot of ACU Closing Prices (Last 4 Years)\") +\n",
        "  xlab(\"Time\") +\n",
        "  ylab(\"Closing Price (USD)\") +\n",
        "  theme_minimal()\n",
        "\n",
        "print(plot_ts)\n",
        "ggsave(\"plots/acu_time_series.png\", plot_ts, width = 10, height = 6)\n",
        "\n",
        "# Part 3: Train-Test Split\n",
        "# ------------------------\n",
        "\n",
        "# 2. Create appropriate train and test sets (80-20 split)\n",
        "message(\"Splitting data into training and test sets (80-20)...\")\n",
        "train_size <- floor(0.8 * length(y_ts))\n",
        "train_set <- window(y_ts, end = c(time(y_ts)[train_size]))\n",
        "test_set <- window(y_ts, start = c(time(y_ts)[train_size + 1]))\n",
        "\n",
        "# Plot train-test split\n",
        "plot_split <- autoplot(y_ts) +\n",
        "  autolayer(train_set, series = \"Training\", color = \"blue\") +\n",
        "  autolayer(test_set, series = \"Testing\", color = \"red\") +\n",
        "  ggtitle(\"Training and Test Split for ACU Stock Data\") +\n",
        "  xlab(\"Time\") +\n",
        "  ylab(\"Closing Price (USD)\") +\n",
        "  theme_minimal() +\n",
        "  theme(legend.position = \"bottom\")\n",
        "\n",
        "print(plot_split)\n",
        "ggsave(\"plots/train_test_split.png\", plot_split, width = 10, height = 6)\n",
        "\n",
        "# Part 4: ARIMA Modeling\n",
        "# ----------------------\n",
        "\n",
        "# 3. Identify an appropriate ARIMA model based on the train set\n",
        "message(\"Fitting ARIMA model...\")\n",
        "auto_arima_model <- auto.arima(train_set, seasonal = TRUE)\n",
        "arima_summary <- capture.output(summary(auto_arima_model))\n",
        "writeLines(arima_summary, \"results/arima_model_summary.txt\")\n",
        "\n",
        "# 4. Residual diagnostic checking of the ARIMA model\n",
        "png(\"plots/arima_residuals.png\", width = 800, height = 600)\n",
        "checkresiduals(auto_arima_model)\n",
        "dev.off()\n",
        "\n",
        "# 5. Use ARIMA model to forecast for the length of the test set\n",
        "arima_forecast <- forecast(auto_arima_model, h = length(test_set))\n",
        "\n",
        "# Plot ARIMA forecast\n",
        "plot_arima_forecast <- autoplot(arima_forecast) +\n",
        "  autolayer(test_set, series = \"Actual\", color = \"red\") +\n",
        "  ggtitle(\"ARIMA Forecast for ACU Closing Prices\") +\n",
        "  xlab(\"Time\") +\n",
        "  ylab(\"Forecasted Closing Price (USD)\") +\n",
        "  theme_minimal() +\n",
        "  theme(legend.position = \"bottom\")\n",
        "\n",
        "print(plot_arima_forecast)\n",
        "ggsave(\"plots/arima_forecast.png\", plot_arima_forecast, width = 10, height = 6)\n",
        "\n",
        "# Part 5: ETS Modeling\n",
        "# --------------------\n",
        "\n",
        "# 6. Identify an appropriate ETS model based on the same train set\n",
        "message(\"Fitting ETS model...\")\n",
        "ets_model <- stlf(train_set, method = \"ets\")\n",
        "ets_summary <- capture.output(summary(ets_model$model))\n",
        "writeLines(ets_summary, \"results/ets_model_summary.txt\")\n",
        "\n",
        "# 7. Residual diagnostic checking of the ETS model\n",
        "png(\"plots/ets_residuals.png\", width = 800, height = 600)\n",
        "checkresiduals(ets_model)\n",
        "dev.off()\n",
        "\n",
        "# 8. Use ETS model to forecast for the length of the test set\n",
        "ets_forecast <- forecast(ets_model, h = length(test_set))\n",
        "\n",
        "# Plot ETS forecast\n",
        "plot_ets_forecast <- autoplot(ets_forecast) +\n",
        "  autolayer(test_set, series = \"Actual\", color = \"red\") +\n",
        "  ggtitle(\"ETS Forecast for ACU Closing Prices\") +\n",
        "  xlab(\"Time\") +\n",
        "  ylab(\"Forecasted Closing Price (USD)\") +\n",
        "  theme_minimal() +\n",
        "  theme(legend.position = \"bottom\")\n",
        "\n",
        "print(plot_ets_forecast)\n",
        "ggsave(\"plots/ets_forecast.png\", plot_ets_forecast, width = 10, height = 6)\n",
        "\n",
        "# Part 6: Model Comparison\n",
        "# ------------------------\n",
        "\n",
        "# 9. Compare the two models\n",
        "# Calculate accuracy metrics for both forecasts\n",
        "arima_accuracy <- accuracy(arima_forecast, test_set)\n",
        "ets_accuracy <- accuracy(ets_forecast, test_set)\n",
        "\n",
        "# Store accuracy results\n",
        "accuracy_results <- rbind(\n",
        "  data.frame(Model = \"ARIMA\", t(arima_accuracy[2, ])),\n",
        "  data.frame(Model = \"ETS\", t(ets_accuracy[2, ]))\n",
        ")\n",
        "write.csv(accuracy_results, \"results/accuracy_comparison.csv\", row.names = FALSE)\n",
        "\n",
        "# 10. Cross-validation\n",
        "message(\"Performing cross-validation...\")\n",
        "\n",
        "# Cross-validation function for ARIMA model\n",
        "arima_cv <- function(train_set, h) {\n",
        "  forecast(auto.arima(train_set), h = h)\n",
        "}\n",
        "\n",
        "# Cross-validation function for ETS model\n",
        "ets_cv <- function(train_set, h) {\n",
        "  forecast(ets(train_set), h = h)\n",
        "}\n",
        "\n",
        "# Perform cross-validation for ARIMA model\n",
        "arima_cv_errors <- tsCV(train_set, arima_cv, h = 1)\n",
        "\n",
        "# Perform cross-validation for ETS model\n",
        "ets_cv_errors <- tsCV(train_set, ets_cv, h = 1)\n",
        "\n",
        "# Calculate cross-validation MSE for both models\n",
        "arima_cv_mse <- mean(arima_cv_errors^2, na.rm = TRUE)\n",
        "ets_cv_mse <- mean(ets_cv_errors^2, na.rm = TRUE)\n",
        "\n",
        "# Store cross-validation results\n",
        "cv_results <- data.frame(\n",
        "  Model = c(\"ARIMA\", \"ETS\"),\n",
        "  MSE = c(arima_cv_mse, ets_cv_mse)\n",
        ")\n",
        "write.csv(cv_results, \"results/cross_validation_results.csv\", row.names = FALSE)\n",
        "\n",
        "# Compare model performance\n",
        "message(\"\\n=== Model Accuracy Comparison ===\")\n",
        "print(\"ARIMA Model Accuracy:\")\n",
        "print(arima_accuracy)\n",
        "\n",
        "message(\"\\n\")\n",
        "print(\"ETS Model Accuracy:\")\n",
        "print(ets_accuracy)\n",
        "\n",
        "message(\"\\n=== Cross-Validation Results ===\")\n",
        "cat(\"ARIMA Cross-Validation MSE:\", arima_cv_mse, \"\\n\")\n",
        "cat(\"ETS Cross-Validation MSE:\", ets_cv_mse, \"\\n\")\n",
        "\n",
        "# Determine which model performed better\n",
        "if (arima_cv_mse < ets_cv_mse) {\n",
        "  cat(\"\\nBased on cross-validation, ARIMA performs better.\\n\")\n",
        "} else {\n",
        "  cat(\"\\nBased on cross-validation, ETS performs better.\\n\")\n",
        "}\n",
        "\n",
        "# Part 7: Combined Visualization\n",
        "# ------------------------------\n",
        "\n",
        "# Create combined plot for forecasting comparison\n",
        "plot_comparison <- autoplot(y_ts) +\n",
        "  autolayer(arima_forecast, series = \"ARIMA\", PI = FALSE, color = \"blue\") +\n",
        "  autolayer(ets_forecast, series = \"ETS\", PI = FALSE, color = \"red\") +\n",
        "  autolayer(test_set, series = \"Actual\", color = \"black\") +\n",
        "  ggtitle(\"Comparison of ARIMA and ETS Forecasts for ACU Stock\") +\n",
        "  xlab(\"Time\") +\n",
        "  ylab(\"Closing Price (USD)\") +\n",
        "  theme_minimal() +\n",
        "  theme(legend.position = \"bottom\")\n",
        "\n",
        "print(plot_comparison)\n",
        "ggsave(\"plots/forecast_comparison.png\", plot_comparison, width = 10, height = 6)\n",
        "\n",
        "message(\"Analysis complete. Results are stored in 'results' and 'plots' directories.\")\n"
      ]
    }
  ]
}
