{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "ir",
      "display_name": "R"
    },
    "language_info": {
      "name": "R"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "a-BLUpRQb0v7"
      },
      "outputs": [],
      "source": [
        "###############################################################\n",
        "# Helper Functions for Time Series Analysis\n",
        "# Author: MITESH KUMAR (M23MAC004)\n",
        "# Date: March 2025\n",
        "###############################################################\n",
        "\n",
        "# Function to calculate additional performance metrics\n",
        "calculate_performance_metrics <- function(forecast_obj, test_data) {\n",
        "  # Get point forecasts\n",
        "  point_forecasts <- forecast_obj$mean\n",
        "\n",
        "  # Calculate forecasting errors\n",
        "  errors <- test_data - point_forecasts\n",
        "\n",
        "  # Calculate additional metrics\n",
        "  metrics <- list(\n",
        "    # Basic metrics (already in accuracy function but included for completeness)\n",
        "    ME = mean(errors, na.rm = TRUE),\n",
        "    RMSE = sqrt(mean(errors^2, na.rm = TRUE)),\n",
        "    MAE = mean(abs(errors), na.rm = TRUE),\n",
        "\n",
        "    # Additional metrics\n",
        "    MASE = mean(abs(errors)) / mean(abs(diff(test_data))),\n",
        "    R_squared = 1 - sum(errors^2) / sum((test_data - mean(test_data))^2),\n",
        "\n",
        "    # Direction accuracy - percentage of times forecast correctly predicts up/down movement\n",
        "    DA = mean(sign(diff(c(NA, point_forecasts))) == sign(diff(c(NA, test_data))), na.rm = TRUE)\n",
        "  )\n",
        "\n",
        "  return(metrics)\n",
        "}\n",
        "\n",
        "# Function to plot ACF and PACF\n",
        "plot_acf_pacf <- function(time_series, filename = NULL) {\n",
        "  par(mfrow = c(2, 1))\n",
        "  acf(time_series, main = \"Autocorrelation Function (ACF)\")\n",
        "  pacf(time_series, main = \"Partial Autocorrelation Function (PACF)\")\n",
        "\n",
        "  if (!is.null(filename)) {\n",
        "    dev.copy(png, filename, width = 800, height = 600)\n",
        "    dev.off()\n",
        "    par(mfrow = c(1, 1))\n",
        "  }\n",
        "}\n",
        "\n",
        "# Function to test stationarity\n",
        "test_stationarity <- function(time_series) {\n",
        "  # Augmented Dickey-Fuller test\n",
        "  adf_test <- adf.test(time_series)\n",
        "\n",
        "  # KPSS test\n",
        "  kpss_test <- kpss.test(time_series)\n",
        "\n",
        "  # Return results\n",
        "  results <- list(\n",
        "    adf = list(\n",
        "      statistic = adf_test$statistic,\n",
        "      p_value = adf_test$p.value,\n",
        "      is_stationary = adf_test$p.value < 0.05\n",
        "    ),\n",
        "    kpss = list(\n",
        "      statistic = kpss_test$statistic,\n",
        "      p_value = kpss_test$p.value,\n",
        "      is_stationary = kpss_test$p.value >= 0.05\n",
        "    )\n",
        "  )\n",
        "\n",
        "  # Overall conclusion\n",
        "  results$conclusion <- ifelse(\n",
        "    results$adf$is_stationary && results$kpss$is_stationary,\n",
        "    \"Series is stationary\",\n",
        "    \"Series may not be stationary\"\n",
        "  )\n",
        "\n",
        "  return(results)\n",
        "}\n",
        "\n",
        "# Function to create seasonal decomposition plot\n",
        "plot_decomposition <- function(time_series, frequency = NULL, filename = NULL) {\n",
        "  # If frequency is not provided, use the frequency of the time series\n",
        "  if (is.null(frequency)) {\n",
        "    frequency <- frequency(time_series)\n",
        "  }\n",
        "\n",
        "  # Perform decomposition\n",
        "  decomp <- stl(time_series, s.window = \"periodic\")\n",
        "\n",
        "  # Plot decomposition\n",
        "  plot_decomp <- autoplot(decomp) +\n",
        "    ggtitle(\"Seasonal Decomposition of Time Series\") +\n",
        "    theme_minimal()\n",
        "\n",
        "  if (!is.null(filename)) {\n",
        "    ggsave(filename, plot_decomp, width = 10, height = 8)\n",
        "  }\n",
        "\n",
        "  return(decomp)\n",
        "}\n",
        "\n",
        "# Function to compare multiple forecast methods visually\n",
        "compare_forecasts <- function(actual, forecasts_list, title = \"Forecast Comparison\", filename = NULL) {\n",
        "  # Create base plot with actual values\n",
        "  plot <- autoplot(actual, series = \"Actual\", color = \"black\", size = 1)\n",
        "\n",
        "  # Add each forecast\n",
        "  colors <- c(\"red\", \"blue\", \"green\", \"purple\", \"orange\", \"brown\")\n",
        "\n",
        "  for (i in 1:length(forecasts_list)) {\n",
        "    forecast_name <- names(forecasts_list)[i]\n",
        "    forecast_obj <- forecasts_list[[i]]\n",
        "    color_idx <- (i - 1) %% length(colors) + 1\n",
        "\n",
        "    plot <- plot +\n",
        "      autolayer(forecast_obj, series = forecast_name, PI = FALSE,\n",
        "                color = colors[color_idx])\n",
        "  }\n",
        "\n",
        "  # Add title and labels\n",
        "  plot <- plot +\n",
        "    ggtitle(title) +\n",
        "    xlab(\"Time\") +\n",
        "    ylab(\"Value\") +\n",
        "    theme_minimal() +\n",
        "    theme(legend.position = \"bottom\")\n",
        "\n",
        "  # Save if filename provided\n",
        "  if (!is.null(filename)) {\n",
        "    ggsave(filename, plot, width = 10, height = 6)\n",
        "  }\n",
        "\n",
        "  return(plot)\n",
        "}\n",
        "\n",
        "# Function to evaluate multiple models using multiple metrics\n",
        "evaluate_models <- function(models_list, test_data) {\n",
        "  # Initialize results data frame\n",
        "  metrics <- c(\"ME\", \"RMSE\", \"MAE\", \"MPE\", \"MAPE\", \"MASE\", \"ACF1\", \"Theil's U\")\n",
        "  results <- data.frame(matrix(NA, nrow = length(models_list), ncol = length(metrics)))\n",
        "  colnames(results) <- metrics\n",
        "  rownames(results) <- names(models_list)\n",
        "\n",
        "  # Calculate metrics for each model\n",
        "  for (i in 1:length(models_list)) {\n",
        "    model_name <- names(models_list)[i]\n",
        "    model_forecast <- models_list[[i]]\n",
        "\n",
        "    # Get accuracy measures\n",
        "    acc <- accuracy(model_forecast, test_data)[2, ]  # Test set row\n",
        "\n",
        "    # Add to results\n",
        "    results[model_name, names(acc)] <- acc\n",
        "  }\n",
        "\n",
        "  return(results)\n",
        "}\n"
      ]
    }
  ]
}
